#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require_relative 'ls_command'

def options
  opt = OptionParser.new
  params = {}
  opt.on('-a') { |v| params[:a] = v }
  opt.on('-r') { |v| params[:r] = v }
  opt.on('-l') { |v| params[:l] = v }
  opt.parse!(ARGV)
  params
end

ls_command = LsCommand.new(options)
ls_command.execute
