#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

COLUMN = 3

def main
  params = options
  resources = target_resources(params)
  sorted_resources = sort_resources(resources)
  if params[:l]
    formatted_resources = format_resources_for_l(sorted_resources)
    display_resources_for_l(formatted_resources)
  else
    formatted_resources = format_resources(sorted_resources)
    display_resources(formatted_resources)
  end
end

def options
  opt = OptionParser.new
  params = {}
  opt.on('-l') { |v| params[:l] = v }
  opt.parse!(ARGV)
  params
end

def target_resources(params)
  resources = Dir.children('.')
  resources.reject { |file| file.start_with?('.') }
end

def sort_resources(resources)
  resources.sort_by { |resource| resource.downcase.gsub(/[.\-_]/, '') }
end

def format_resources(resources)
  column_number = (resources.size + COLUMN - 1) / COLUMN
  exit if column_number.zero?
  sliced_resources = resources.each_slice(column_number).to_a
  alligned_resources = sliced_resources.map do |names|
    names.map { |name| name.ljust(names.map(&:size).max + 2) }
  end
  (column_number - alligned_resources[-1].size).times { alligned_resources[-1] << nil }
  alligned_resources.transpose
end

def format_resources_for_l(resources)
  files = []
  formatted_resources = []
  resources.each { |resource| files << File.new(File.absolute_path(resource)) }
  files.each do |file|
    permission = file
    hard_link_count = file
    user = file
    group = file
    size = file
    stamp = file
    formatted_resources << [permission, hard_link_count, user, group, size, stamp]
  end
  # ここでpermission以降の要素の縦列の長さを揃える処理が必要

  formatted_resources
end

def to_permissions(binary)
  binary.chars.each_slice(3).each do |aaa|
    
  end
end

def display_resources(resources)
  resources.each do |column|
    puts column.compact.join
  end
end

def display_resources_for_l(resources)
end

main
