#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'etc'

def main
  params = options
  display_types = display_types(params)
  args = ARGV
  if args.any?
    file_details = file_details(args)
    display_wc(file_details, display_types)
    display_total_wc(file_details, display_types) if file_details.size >= 2
  else
    buffer = $stdin.read
    display_wc_for_stdin(buffer, display_types)
  end
end

def options
  opt = OptionParser.new
  params = {}
  opt.on('-l') { |v| params[:l] = v }
  opt.on('-w') { |v| params[:w] = v }
  opt.on('-c') { |v| params[:c] = v }
  opt.parse!(ARGV)
  params
end

def display_types(params)
  types = []
  types << :nline if params[:l] || params.empty?
  types << :nword if params[:w] || params.empty?
  types << :byte_size if params[:c] || params.empty?
  types
end

def file_details(args)
  args.map do |arg|
    file = File.new(arg)
    content = file.read
    nline = content.count("\n")
    nword = content.gsub(/\t|\n/, ' ').strip.squeeze(' ').count(' ') + 1
    byte_size = file.size
    { nline:, nword:, byte_size:, name: arg }
  end
end

def display_wc(file_details, display_types)
  max_digit = file_details.sum { |file_detail| file_detail[:byte_size] }.to_s.size
  file_details.each do |file_detail|
    details = display_types.map { |type| file_detail[type].to_s.rjust(max_digit, ' ') }
    details = details.map(&:strip) if file_details.size == 1 && details.size == 1
    puts details.push(file_detail[:name]).join(' ')
  end
end

def display_total_wc(file_details, display_types)
  max_digit = file_details.sum { |file_detail| file_detail[:byte_size] }.to_s.size
  details = display_types.map do |type|
    file_details.sum { |file| file[type] }.to_s.rjust(max_digit, ' ')
  end
  puts details.push('total').join(' ')
end

def display_wc_for_stdin(buffer, display_types)
  details = {
    nline: buffer.count("\n"),
    nword: buffer.gsub(/\t|\n/, ' ').strip.squeeze(' ').count(' ') + 1,
    byte_size: buffer.bytesize
  }
  target_details = display_types.map { |type| details[type].to_s.rjust(7, ' ') }
  target_details = target_details.map(&:strip) if target_details.size == 1
  puts target_details.join(' ')
end

main
